# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Fluffy Radio
email: hello@fluffyradio.com
description: > # this means to ignore newlines until "baseurl:"
  Playing the music you want to hear, Fluffy Radio, packs all of the hits.  In short, we play anything and everything... Pure Fluff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.fluffyradio.com" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: UA-41168228-5

# Build settings
markdown: kramdown
# theme: minima
sass:
  style: compressed
gems:
  - github-pages
  - font-awesome-sass
exclude:
  - Gemfile
  - Gemfile.lock
# Navigation List
navigation:
  - title: Home
    url: /
  - title: Music
    url: /music/
  - title: Store
    url: https://store.fluffyradio.com
